openapi: 3.0.1
info:
  title: Test API
  description: Mule 4.3 features testing API
  version: v1
servers:
- url: https://testmulesoft4.3.com/
security:
- Authorization: []
tags:
- name: internal features API
  description: APIs related to mule 4.3
- name: custom features API
  description: APIs related to custom features
paths:
  /testFeature1:
    get:
      tags:
      - internal features API
      summary: Ping
      description: This API will be used to testFeature1
      operationId: testFeature1
      parameters:
      - name: Content-Type
        in: header
        description: Indicates the media type of the resource
        schema:
          type: string
          default: application/json
      responses:
        "200":
          description: Success response
          content: {}
        "400":
          description: This indicates that the server cannot or will not process the
            request due to something that is perceived to be a client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example: |-
                {
                  "errors": [{
                    "category": "API_ERROR",
                    "code": "MISSING_REQUIRED_PARAMETER",
                    "detail": "Missing required parameter"
                  }]
                }
        "500":
          description: This indicates that the server encountered an unexpected condition
            that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                errorResponse:
                  value:
                    {
                      "errors": [{
                        "category": "API_ERROR",
                        "code": "INTERNAL_SERVER_ERROR",
                        "detail": "Request could not be completed due to some error" 
                      }]
                    }
  /redisTest:
    get:
      tags:
      - internal features API
      summary: Ping
      description: This API will be used to test redis
      operationId: redisTest
      parameters:
      - name: Content-Type
        in: header
        description: Indicates the media type of the resource
        schema:
          type: string
          default: application/json
      - name: id
        in: header
        description: Id we are referring to
        schema:
          type: string
          default: application/json
      responses:
        "200":
          description: Success response
          content: 
            application/json:
              schema:
                  $ref: "#/components/schemas/kafkaTestRequest"  
        "400":
          description: This indicates that the server cannot or will not process the
            request due to something that is perceived to be a client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example: |-
                {
                  "errors": [{
                    "category": "API_ERROR",
                    "code": "MISSING_REQUIRED_PARAMETER",
                    "detail": "Missing required parameter"
                  }]
                }
        "500":
          description: This indicates that the server encountered an unexpected condition
            that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                errorResponse:
                  value:
                    {
                      "errors": [{
                        "category": "API_ERROR",
                        "code": "INTERNAL_SERVER_ERROR",
                        "detail": "Request could not be completed due to some error" 
                      }]
                    }
  /kafkaTest:
    post:
      tags:
      - internal features API
      summary: Ping
      description: This API will be used to test redis POST
      operationId: redisTestPost
      parameters:
      - name: Content-Type
        in: header
        description: Indicates the media type of the resource
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: Informs the server about the types of data that can be sent back
        schema:
          type: string
          default: application/json
      requestBody:
        description: Kafka Test Request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/kafkaTestRequest"  
      responses:
        "201":
          description: Success response
          content: {}
        "400":
          description: This indicates that the server cannot or will not process the
            request due to something that is perceived to be a client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example: |-
                {
                  "errors": [{
                    "category": "API_ERROR",
                    "code": "MISSING_REQUIRED_PARAMETER",
                    "detail": "Missing required parameter"
                  }]
                }
        "500":
          description: This indicates that the server encountered an unexpected condition
            that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                errorResponse:
                  value:
                    {
                      "errors": [{
                        "category": "API_ERROR",
                        "code": "INTERNAL_SERVER_ERROR",
                        "detail": "Request could not be completed due to some error" 
                      }]
                    }
components:
  schemas:
    kafkaTestRequest:
      type: object
      properties:
        id:
          type: string
          description: sampleType1
          default: sampleType1
        status:
          type: string
          description: sampleType2
          default: fail
          enum:
          - pass
          - fail
      required: [id, status]
    error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
                description: category for the error code
              code:
                type: string
                description: error code corresponding to each request
              detail:
                type: string
                description: Generic failure message
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      description: Indicates the media type of the resource
      schema:
        type: string
        default: application/json
    Accept:
      name: Accept
      in: header
      description: Informs the server about the types of data that can be sent back
      schema:
        type: string
        default: application/json
  securitySchemes:
    Authorization:
      type: apiKey
      description: The authorization token received from Token API
      name: Authorization
      in: header
